In [9]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd

In [10]:
dfglobal = pd.read_csv("Classification/all_files_globalv1.csv")
dfza = pd.read_csv("Classification/all_files_ZAv1.csv")
dfskr = pd.read_csv("Classification/all_files_skrv1.csv")

dfskr=dfskr.drop_duplicates()

In [12]:
dfskr.columns

Index(['trackAppearanceCount', 'artistAppearanceCount', 'rank', 'uri',
       'artist_names', 'track_name', 'source', 'peak_rank', 'previous_rank',
       'weeks_on_chart', 'streams', 'End Date', 'Week', 'Year', 'End Date Dt',
       'Seconds since Epoch', 'End Date Aggregated', 'ArtistCount',
       'main_artist', 'isTopTen', 'Artist and Track', 'rank difference',
       'Position over Time', 'IsGirlGroup', 'IsBoyGroup'],
      dtype='object')

In [4]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])

kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [5]:
kmeans.labels_


array([1, 1, 1, 0, 0, 0])

In [6]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0])

In [7]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])